 const AUTHTYPES = {

    SIGN_IN_START: "SIGN_IN_START",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAIL: "SIGN_IN_FAIL",

    SIGN_UP_START: "SIGN_UP_START",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_FAIL: "SIGN_UP_FAIL",
    RESET_SIGN_UP_STATE: "RESET_SIGN_UP_STATE",
    AUTH_RESET: 'AUTH_RESET'
}
export default AUTHTYPES