const CODETYPES = {
    GET_CODE_START: "GET_CODE_START",
    GET_CODE_SUCCESS: "GET_CODE_SUCCESS",
    GET_CODE_FAIL: "GET_CODE_FAIL",
    GET_CODE_RESET: "GET_CODE_RESET",
};
export default CODETYPES;
