const REPOSITORY_TYPES = {
    GET_REPO_ALL_START: "GET_REPO_ALL_START",
    GET_REPO_ALL_SUCCESS: "GET_REPO_ALL_SUCCESS",
    GET_REPO_ALL_FAIL: "GET_REPO_ALL_FAIL",
    GET_REPO_ALL_RESET: "GET_REPO_ALL_RESET",
}
export default REPOSITORY_TYPES;